%%plantuml

@startuml
actor Listener #cyan
participant "Podcasting 2.0\nmobile/web app " as App #99FF99
participant "PodcastIndex.org\nAPI" as Ind #red
participant "Bitcoin Lightning\nwallet" as Btc #orange
actor Podcaster #violet
Podcaster->Ind: register your podcast
Listener->App: Download & Install
App->Ind: call to find podcasts
Listener->App: Subscribe to a podcast
Listener->Btc: buy Bitcoin and convert it to Bitcoin Lightning
Listener->App: request invoice of\nBitcoin Lightning\nto charge podcatcher app
Listener->Btc: pay the invoice by pasting it as text
Btc->App: transfer Bitcoin Lightning 
Listener->App: stream satoshis\nor send boostogram\nor boost
App->Podcaster: transfer Bitcoin Lightning + boostogram messages
@enduml
